### ISSUE TITLE
What is session

### ISSUE THREAD

**Issue by Akshit1025** [azad71/Library-Management-System#7]
Hey I really liked this repo and I want to make it work locally on my system but for that, I'll be needing the `session_secret` so I want to know what that is?

**Comment by azad71** [comment]
session secret is server side secret to compute hash. Putting a random string should work. For details, [check this out](https://stackoverflow.com/questions/5343131/what-is-the-sessions-secret-option)

**Comment by Akshit1025** [comment]
ok thanks

**Comment by Akshit1025** [comment]
can you also write a wiki page on where to get the keys of the `.env` file and which variable is for what ??

thanks

**Comment by azad71** [comment]
Oh yeah, sure, that'd be nice. In fact, I am trying to renovate this repo for years. I just can't manage time for it :). Will do it in future

**Comment by Akshit1025** [comment]
ok thank you
